name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD:   ${{ secrets.DOCKER_PASSWORD}}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    - name: Build Docker Image
      run: |
        docker build -t jdominguezhub/ticketplus-find:1.0.1 .
        docker build -t jdominguezhub/ticketplus-find:latest .

    - name: Push Docker Image
      run: |
        docker push jdominguezhub/ticketplus-find:1.0.1
        docker push jdominguezhub/ticketplus-find:latest
    - name: Notify DigitalOcean
      run: |
        curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" "https://api.digitalocean.com/v2/apps/20ac3b98-a4c8-4734-8393-ed8625b43749/deployments"


      
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
